In [1]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
iris_path = "/content/drive/MyDrive/ML/Lab 7/iris.csv"
df = pd.read_csv(iris_path)

In [3]:
def discretize(df):
  for i in list(df):
    if i != "variety":
      col = df[i]
      print(i)
      bins = pd.cut(col, 3, labels = ["1", "2", "3"]) # Discretizes to bins
      df[i] = bins

In [4]:
discretize(df)

sepal.length
sepal.width
petal.length
petal.width


In [5]:
y = df['variety']
X = df.drop(['variety'], axis = 1)

In [6]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
cnb = CategoricalNB()
y_pred = cnb.fit(X_train, y_train).predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Test Accuracy:  0.9666666666666667
Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
