In [1]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install mlxtend -U

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 5.2 MB/s 
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.14.0
    Uninstalling mlxtend-0.14.0:
      Successfully uninstalled mlxtend-0.14.0


In [3]:
iris_path = "/content/drive/MyDrive/ML/Lab 7/iris.csv"
df = pd.read_csv(iris_path)

In [4]:
def discretize(df):
  for i in list(df):
    if i != "variety":
      col = df[i]
      print(i)
      bins = pd.cut(col, 3, labels = ["1", "2", "3"]) # Discretizes to bins
      df[i] = bins

In [5]:
discretize(df)

sepal.length
sepal.width
petal.length
petal.width


In [6]:
y = df['variety']
X = df.drop(['variety'], axis = 1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
X_train = np.array(X_train.to_numpy(),dtype='float64')
y_train = y_train.to_numpy()
X_test = np.array(X_test.to_numpy(),dtype='float64')
y_test = y_test.to_numpy()
_, y_train = np.unique(y_train, return_inverse=True)
_, y_test = np.unique(y_test, return_inverse=True)

In [8]:
from mlxtend.classifier import OneRClassifier
oner = OneRClassifier()
oner.fit(X_train, y_train)
y_pred = oner.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Attribute:", list(X)[oner.feature_idx_])
print("Rules:", oner.prediction_dict_)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Test Accuracy: 0.9666666666666667
Attribute: petal.width
Rules: {'total error': 5, 'rules (value: class)': {1.0: 0, 2.0: 1, 3.0: 2}}

Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
