In [1]:
import numpy as np
import pandas as pd
from google.colab import drive
import time
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
iris_path = "/content/drive/MyDrive/ML/Lab 8/iris.csv"
df = pd.read_csv(iris_path)

In [3]:
def discretize(df):
  for i in list(df):
    if i != "variety":
      col = df[i]
      print(i)
      bins = pd.cut(col, 3, labels = ["1", "2", "3"]) # Discretizes to bins
      df[i] = bins

In [4]:
discretize(df)

sepal.length
sepal.width
petal.length
petal.width


In [5]:
y = df['variety']
X = df.drop(['variety'], axis = 1)

In [6]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
start = time.perf_counter()
model = RandomForestClassifier()

y_pred = model.fit(X_train, y_train).predict(X_test)
end = time.perf_counter()

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Time:", end - start)

Test Accuracy:  1.0
Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Time: 0.3834061760000509


In [8]:
from sklearn.ensemble import AdaBoostClassifier
start = time.perf_counter()
model = AdaBoostClassifier()

y_pred = model.fit(X_train, y_train).predict(X_test)
end = time.perf_counter()

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Test Accuracy: ", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Time:", end - start)

Test Accuracy:  1.0
Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Time: 0.18164871199996924
